<a href="https://colab.research.google.com/github/aarmentamna/PY0101EN/blob/main/M5Numpy2DArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Arreglos 2D Numpy**


In [5]:
import numpy as np

Dimensional Numpy Arrays

In [8]:
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A[0][0])
print(A[0,0:3])

2
(3, 3)
9
11
[11 12 13]


In [15]:
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[2,1]])
Z = X + Y
Z

array([[3, 1],
       [2, 2]])

In [17]:
S = X * Y
print(S)
M = 2*Y
print(M)

[[2 0]
 [0 1]]
[[4 2]
 [4 2]]


In [19]:
G = np.array([[0,1,1],[1,0,1]])
R = np.array([[1,1],[1,1],[-1,1]])
C = np.dot(G,R)
C

array([[0, 2],
       [0, 2]])

Preguntas Module 5

In [6]:


A = np.array([[1,2],[3,4],[5,6],[7,8]])
A.size

8

In [7]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(A,B)

ValueError: ignored

In [20]:
import matplotlib.pyplot as plt

In [21]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [22]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [23]:
print(A.ndim)
print(A.shape)
print(A.size)

2
(3, 3)
9


In [29]:
c = [[11,12,13],[21,22,23],[31,32,33]]

print(c[0][0])


11


In [30]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 
Z = X + Y
print(Z)


[[3 1]
 [1 3]]


In [31]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])
H = np.dot(A,B)
print(H)
print(np.sin(H))

[[0 2]
 [0 2]]
[[0.         0.90929743]
 [0.         0.90929743]]
